export const validationMessages = {
    endpointNotFound: "Can't find endpoint on this server!",
    methodNotAllowed: 'Method not allowed',
    tooManyRequests: 'Too Many Requests from this IP, please try again in 10 minutes.',
    notLoggedIn: 'You are not logged in! Please log in to get access.',
    invalidToken: 'Token does not belong to any existing user.',
    notAuthorized: 'You are not authorized.',
    invalidCredentials: 'Invalid credentials',
    userIdNotValid: 'Invalid user ID',
    demoIdNotValid: 'Invalid demo ID',
    userNotFound: 'User not found',
    demoNotFound: 'Demo not found',
    emailIsRequired: 'Please add an email.',
    firstNameIsRequired: 'Please add a first name.',
    lastNameIsRequired: 'Please add a last name.',
    passwordIsRequired: 'Please add a password.',
    invalidEmail: 'Please add a valid email.',
    emailAlreadyRegistered: 'The email is already registered',
    passwordLessThanXCharacters: 'Password must be at least 6 characters.',
    passwordGreaterThanXCharacters: 'Password must be at most 30 characters.',
    demoNameIsRequired: 'Please add a demo name'
};
